#!/usr/bin/env bash

# Crear el directorio locales si no existe
mkdir -p locales

echo "Generando archivos YAML de traducciones para Dialoom..."

# Español (es.yaml)
cat << 'EOF' > locales/es.yaml
errors:
  unexpected_error: "Ha ocurrido un error inesperado. Por favor, inténtalo de nuevo más tarde."
  invalid_credentials: "Usuario o contraseña incorrectos."
  unauthorized: "No estás autorizado para realizar esta acción."
  forbidden: "Acceso prohibido."
  not_found: "Recurso no encontrado."
  user_not_found: "Usuario no encontrado."
  email_exists: "Esta dirección de correo electrónico ya está en uso."
  username_exists: "Este nombre de usuario ya está en uso."
  account_disabled: "Esta cuenta ha sido deshabilitada."
  session_expired: "La sesión ha expirado. Por favor, inicia sesión de nuevo."
  rate_limit: "Demasiadas solicitudes. Por favor, inténtalo de nuevo más tarde."
  server_error: "Error interno del servidor."
validation:
  required_field: "Este campo es obligatorio."
  invalid_email: "Por favor, introduzca una dirección de correo electrónico válida."
  min_length: "Debe tener al menos {min} caracteres."
  max_length: "Debe tener como máximo {max} caracteres."
  password_mismatch: "Las contraseñas no coinciden."
  invalid_format: "Formato no válido."
  only_numbers: "Solo se permiten valores numéricos."
  min_value: "El valor debe ser como mínimo {min}."
  max_value: "El valor debe ser como máximo {max}."
  too_short: "Demasiado corto."
  too_long: "Demasiado largo."
notifications:
  new_message: "Nuevo mensaje de {name}."
  friend_request: "Tienes una nueva solicitud de amistad."
  meeting_reminder: "Recordatorio: Reunión \"{title}\" a las {time}."
  task_due_soon: "La tarea \"{task}\" vence pronto."
  new_notification: "Tienes una nueva notificación."
  promo_offer: "Nueva oferta promocional disponible."
  account_approved: "Tu cuenta ha sido aprobada."
  account_rejected: "Tu cuenta ha sido rechazada."
  update_available: "Hay una nueva actualización disponible."
  event_starting: "El evento \"{event}\" está comenzando ahora."
emails:
  welcome_subject: "¡Bienvenido a Dialoom!"
  welcome_body: "Hola {name},\n\nGracias por unirte a Dialoom. Estamos encantados de tenerte con nosotros. Si tienes alguna pregunta, no dudes en contactar a nuestro equipo de soporte.\n\nSaludos,\nEl equipo de Dialoom"
  reset_password_subject: "Restablece tu contraseña de Dialoom"
  reset_password_body: "Hola {name},\n\nHemos recibido una solicitud para restablecer tu contraseña. Haz clic en el siguiente enlace para crear una nueva contraseña. Si no solicitaste esto, por favor ignora este correo.\n\nGracias,\nEl equipo de soporte de Dialoom"
  verify_email_subject: "Verifica tu dirección de correo electrónico"
  verify_email_body: "Hola {name},\n\nPor favor, verifica tu dirección de correo electrónico haciendo clic en el siguiente enlace. Si tú no creaste una cuenta de Dialoom, puedes ignorar este correo.\n\nGracias,\nEl equipo de Dialoom"
  password_changed_subject: "Tu contraseña ha sido cambiada"
  password_changed_body: "Hola {name},\n\nEsta es una confirmación de que tu contraseña se ha cambiado exitosamente. Si tú no realizaste este cambio, por favor contacta con nuestro equipo de soporte de inmediato.\n\nSaludos,\nEl equipo de Dialoom"
api:
  created_success: "Creado con éxito."
  updated_success: "Actualizado con éxito."
  deleted_success: "Eliminado con éxito."
  operation_success: "Operación completada con éxito."
  operation_failed: "Operación fallida."
  invalid_token: "Token no válido."
  authentication_required: "Se requiere autenticación."
  permission_denied: "Permiso denegado."
  resource_not_found: "Recurso no encontrado."
  bad_request: "Solicitud incorrecta."
  conflict_error: "Error de conflicto."
  server_error: "Error del servidor."
  service_unavailable: "Servicio no disponible. Por favor, inténtalo de nuevo más tarde."
  too_many_requests: "Demasiadas solicitudes."
  missing_fields: "Faltan campos obligatorios."
  invalid_parameters: "Parámetros no válidos."
  method_not_allowed: "Método no permitido."
  request_timeout: "Tiempo de espera agotado."
general:
  ok: "Aceptar"
  cancel: "Cancelar"
  confirm: "Confirmar"
  yes: "Sí"
  no: "No"
  back: "Atrás"
  next: "Siguiente"
  close: "Cerrar"
  save: "Guardar"
  delete: "Eliminar"
  search: "Buscar"
  login: "Iniciar sesión"
  logout: "Cerrar sesión"
  sign_up: "Registrarse"
  profile: "Perfil"
  settings: "Configuración"
  send: "Enviar"
  submit: "Enviar"
  loading: "Cargando..."
  no_results: "No se encontraron resultados."
  welcome: "¡Bienvenido!"
  goodbye: "¡Adiós!"
  thank_you: "Gracias."
  try_again: "Por favor, inténtalo de nuevo."
  contact_support: "Contacta con soporte."
EOF

# Inglés (en.yaml)
cat << 'EOF' > locales/en.yaml
errors:
  unexpected_error: "An unexpected error occurred. Please try again later."
  invalid_credentials: "Invalid username or password."
  unauthorized: "You are not authorized to perform this action."
  forbidden: "Access forbidden."
  not_found: "Resource not found."
  user_not_found: "User not found."
  email_exists: "This email address is already in use."
  username_exists: "This username is already taken."
  account_disabled: "This account has been disabled."
  session_expired: "Session expired. Please log in again."
  rate_limit: "Too many requests. Please try again later."
  server_error: "Internal server error."
validation:
  required_field: "This field is required."
  invalid_email: "Please enter a valid email address."
  min_length: "Must be at least {min} characters."
  max_length: "Must be at most {max} characters."
  password_mismatch: "Passwords do not match."
  invalid_format: "Invalid format."
  only_numbers: "Only numeric values are allowed."
  min_value: "Value must be at least {min}."
  max_value: "Value must be at most {max}."
  too_short: "Too short."
  too_long: "Too long."
notifications:
  new_message: "New message from {name}."
  friend_request: "You have a new friend request."
  meeting_reminder: "Reminder: Meeting \"{title}\" at {time}."
  task_due_soon: "Task \"{task}\" is due soon."
  new_notification: "You have a new notification."
  promo_offer: "New promotional offer available."
  account_approved: "Your account has been approved."
  account_rejected: "Your account has been rejected."
  update_available: "A new update is available."
  event_starting: "Event \"{event}\" is starting now."
emails:
  welcome_subject: "Welcome to Dialoom!"
  welcome_body: "Hello {name},\n\nThank you for joining Dialoom. We're excited to have you on board. If you have any questions, feel free to contact our support team.\n\nBest regards,\nThe Dialoom Team"
  reset_password_subject: "Reset your Dialoom password"
  reset_password_body: "Hello {name},\n\nWe received a request to reset your password. Click the link below to set a new password. If you didn’t request this, please ignore this email.\n\nThank you,\nDialoom Support"
  verify_email_subject: "Verify your email address"
  verify_email_body: "Hello {name},\n\nPlease verify your email address by clicking the link below. If you did not create a Dialoom account, you can ignore this email.\n\nThank you,\nThe Dialoom Team"
  password_changed_subject: "Your password has been changed"
  password_changed_body: "Hello {name},\n\nThis is a confirmation that your password was successfully changed. If you did not make this change, please contact support immediately.\n\nRegards,\nThe Dialoom Team"
api:
  created_success: "Created successfully."
  updated_success: "Updated successfully."
  deleted_success: "Deleted successfully."
  operation_success: "Operation completed successfully."
  operation_failed: "Operation failed."
  invalid_token: "Invalid token."
  authentication_required: "Authentication is required."
  permission_denied: "Permission denied."
  resource_not_found: "Resource not found."
  bad_request: "Bad request."
  conflict_error: "Conflict error."
  server_error: "Server error."
  service_unavailable: "Service unavailable. Please try again later."
  too_many_requests: "Too many requests."
  missing_fields: "Missing required fields."
  invalid_parameters: "Invalid parameters."
  method_not_allowed: "Method not allowed."
  request_timeout: "Request timeout."
general:
  ok: "OK"
  cancel: "Cancel"
  confirm: "Confirm"
  yes: "Yes"
  no: "No"
  back: "Back"
  next: "Next"
  close: "Close"
  save: "Save"
  delete: "Delete"
  search: "Search"
  login: "Log In"
  logout: "Log Out"
  sign_up: "Sign Up"
  profile: "Profile"
  settings: "Settings"
  send: "Send"
  submit: "Submit"
  loading: "Loading..."
  no_results: "No results found."
  welcome: "Welcome!"
  goodbye: "Goodbye!"
  thank_you: "Thank you."
  try_again: "Please try again."
  contact_support: "Contact support."
EOF

# Catalán (ca.yaml)
cat << 'EOF' > locales/ca.yaml
errors:
  unexpected_error: "S'ha produït un error inesperat. Si us plau, torna-ho a intentar més tard."
  invalid_credentials: "Nom d'usuari o contrasenya incorrectes."
  unauthorized: "No estàs autoritzat a realitzar aquesta acció."
  forbidden: "Accés prohibit."
  not_found: "Recurs no trobat."
  user_not_found: "Usuari no trobat."
  email_exists: "Aquesta adreça de correu electrònic ja està en ús."
  username_exists: "Aquest nom d'usuari ja està en ús."
  account_disabled: "Aquest compte ha estat deshabilitat."
  session_expired: "La sessió ha expirat. Si us plau, inicia sessió de nou."
  rate_limit: "Massa sol·licituds. Si us plau, torna-ho a intentar més tard."
  server_error: "Error intern del servidor."
validation:
  required_field: "Aquest camp és obligatori."
  invalid_email: "Si us plau, introdueix una adreça de correu electrònic vàlida."
  min_length: "Ha de tenir almenys {min} caràcters."
  max_length: "Ha de tenir com a màxim {max} caràcters."
  password_mismatch: "Les contrasenyes no coincideixen."
  invalid_format: "Format no vàlid."
  only_numbers: "Només es permeten valors numèrics."
  min_value: "El valor ha de ser com a mínim {min}."
  max_value: "El valor ha de ser com a màxim {max}."
  too_short: "Massa curt."
  too_long: "Massa llarg."
notifications:
  new_message: "Nou missatge de {name}."
  friend_request: "Tens una nova sol·licitud d'amistat."
  meeting_reminder: "Recordatori: Reunió \"{title}\" a les {time}."
  task_due_soon: "La tasca \"{task}\" venç aviat."
  new_notification: "Tens una nova notificació."
  promo_offer: "Nova oferta promocional disponible."
  account_approved: "El teu compte ha estat aprovat."
  account_rejected: "El teu compte ha estat rebutjat."
  update_available: "Hi ha una nova actualització disponible."
  event_starting: "L'esdeveniment \"{event}\" està començant ara."
emails:
  welcome_subject: "Benvingut a Dialoom!"
  welcome_body: "Hola {name},\n\nGràcies per unir-te a Dialoom. Estem molt contents de tenir-te amb nosaltres. Si tens cap pregunta, no dubtis a contactar amb el nostre equip de suport.\n\nSalutacions,\nL'equip de Dialoom"
  reset_password_subject: "Restableix la teva contrasenya de Dialoom"
  reset_password_body: "Hola {name},\n\nHem rebut una sol·licitud per restablir la teva contrasenya. Fes clic a l'enllaç següent per crear una contrasenya nova. Si no has sol·licitat això, ignora aquest correu electrònic.\n\nGràcies,\nL'equip de suport de Dialoom"
  verify_email_subject: "Verifica la teva adreça de correu electrònic"
  verify_email_body: "Hola {name},\n\nSi us plau, verifica la teva adreça de correu electrònic fent clic a l'enllaç següent. Si no has creat un compte de Dialoom, pots ignorar aquest correu.\n\nGràcies,\nL'equip de Dialoom"
  password_changed_subject: "La teva contrasenya ha estat canviada"
  password_changed_body: "Hola {name},\n\nAquesta és una confirmació que la teva contrasenya s'ha canviat correctament. Si no has fet aquest canvi, contacta immediatament amb el suport.\n\nSalutacions,\nL'equip de Dialoom"
api:
  created_success: "Creat amb èxit."
  updated_success: "Actualitzat amb èxit."
  deleted_success: "Eliminat amb èxit."
  operation_success: "Operació completada amb èxit."
  operation_failed: "Operació fallida."
  invalid_token: "Token no vàlid."
  authentication_required: "Cal autenticació."
  permission_denied: "Permís denegat."
  resource_not_found: "Recurs no trobat."
  bad_request: "Sol·licitud incorrecta."
  conflict_error: "Error de conflicte."
  server_error: "Error de servidor."
  service_unavailable: "Servei no disponible. Si us plau, torna-ho a intentar més tard."
  too_many_requests: "Massa sol·licituds."
  missing_fields: "Falten camps obligatoris."
  invalid_parameters: "Paràmetres no vàlids."
  method_not_allowed: "Mètode no permès."
  request_timeout: "Temps d'espera esgotat."
general:
  ok: "D'acord"
  cancel: "Cancel·lar"
  confirm: "Confirmar"
  yes: "Sí"
  no: "No"
  back: "Atràs"
  next: "Següent"
  close: "Tancar"
  save: "Desar"
  delete: "Eliminar"
  search: "Cercar"
  login: "Inicia sessió"
  logout: "Tanca sessió"
  sign_up: "Registra't"
  profile: "Perfil"
  settings: "Configuració"
  send: "Enviar"
  submit: "Enviar"
  loading: "Carregant..."
  no_results: "No s'han trobat resultats."
  welcome: "Benvingut!"
  goodbye: "Adéu!"
  thank_you: "Gràcies."
  try_again: "Si us plau, torna-ho a intentar."
  contact_support: "Contacta amb el suport."
EOF

# Alemán (de.yaml)
cat << 'EOF' > locales/de.yaml
errors:
  unexpected_error: "Es ist ein unerwarteter Fehler aufgetreten. Bitte versuchen Sie es später noch einmal."
  invalid_credentials: "Benutzername oder Passwort ungültig."
  unauthorized: "Sie sind nicht berechtigt, diese Aktion durchzuführen."
  forbidden: "Zugriff verweigert."
  not_found: "Ressource nicht gefunden."
  user_not_found: "Benutzer nicht gefunden."
  email_exists: "Diese E-Mail-Adresse ist bereits registriert."
  username_exists: "Dieser Benutzername ist bereits vergeben."
  account_disabled: "Dieses Konto wurde deaktiviert."
  session_expired: "Die Sitzung ist abgelaufen. Bitte melden Sie sich erneut an."
  rate_limit: "Zu viele Anfragen. Bitte versuchen Sie es später erneut."
  server_error: "Interner Serverfehler."
validation:
  required_field: "Dieses Feld ist erforderlich."
  invalid_email: "Bitte geben Sie eine gültige E-Mail-Adresse ein."
  min_length: "Muss mindestens {min} Zeichen lang sein."
  max_length: "Darf höchstens {max} Zeichen lang sein."
  password_mismatch: "Passwörter stimmen nicht überein."
  invalid_format: "Ungültiges Format."
  only_numbers: "Es sind nur numerische Werte erlaubt."
  min_value: "Der Wert muss mindestens {min} betragen."
  max_value: "Der Wert darf höchstens {max} betragen."
  too_short: "Zu kurz."
  too_long: "Zu lang."
notifications:
  new_message: "Neue Nachricht von {name}."
  friend_request: "Sie haben eine neue Freundschaftsanfrage."
  meeting_reminder: "Erinnerung: Besprechung \"{title}\" um {time}."
  task_due_soon: "Aufgabe \"{task}\" ist bald fällig."
  new_notification: "Sie haben eine neue Benachrichtigung."
  promo_offer: "Neues Sonderangebot verfügbar."
  account_approved: "Ihr Konto wurde genehmigt."
  account_rejected: "Ihr Konto wurde abgelehnt."
  update_available: "Ein neues Update ist verfügbar."
  event_starting: "Das Ereignis \"{event}\" beginnt jetzt."
emails:
  welcome_subject: "Willkommen bei Dialoom!"
  welcome_body: "Hallo {name},\n\nvielen Dank, dass Sie sich bei Dialoom angemeldet haben. Wir freuen uns, Sie an Bord zu haben. Wenn Sie Fragen haben, können Sie sich gerne an unser Support-Team wenden.\n\nMit freundlichen Grüßen,\nIhr Dialoom-Team"
  reset_password_subject: "Setzen Sie Ihr Dialoom-Passwort zurück"
  reset_password_body: "Hallo {name},\n\nwir haben eine Anfrage zum Zurücksetzen Ihres Passworts erhalten. Klicken Sie auf den untenstehenden Link, um ein neues Passwort festzulegen. Falls Sie diese Anfrage nicht gestellt haben, ignorieren Sie bitte diese E-Mail.\n\nVielen Dank,\nIhr Dialoom-Support-Team"
  verify_email_subject: "Bestätigen Sie Ihre E-Mail-Adresse"
  verify_email_body: "Hallo {name},\n\nbitte bestätigen Sie Ihre E-Mail-Adresse, indem Sie auf den folgenden Link klicken. Wenn Sie kein Dialoom-Konto erstellt haben, können Sie diese E-Mail ignorieren.\n\nVielen Dank,\nIhr Dialoom-Team"
  password_changed_subject: "Ihr Passwort wurde geändert"
  password_changed_body: "Hallo {name},\n\nhiermit bestätigen wir, dass Ihr Passwort erfolgreich geändert wurde. Sollten Sie diese Änderung nicht vorgenommen haben, kontaktieren Sie bitte umgehend unseren Support.\n\nMit freundlichen Grüßen,\nIhr Dialoom-Team"
api:
  created_success: "Erfolgreich erstellt."
  updated_success: "Erfolgreich aktualisiert."
  deleted_success: "Erfolgreich gelöscht."
  operation_success: "Vorgang erfolgreich abgeschlossen."
  operation_failed: "Vorgang fehlgeschlagen."
  invalid_token: "Ungültiges Token."
  authentication_required: "Authentifizierung erforderlich."
  permission_denied: "Zugriff verweigert."
  resource_not_found: "Ressource nicht gefunden."
  bad_request: "Ungültige Anfrage."
  conflict_error: "Konfliktfehler."
  server_error: "Serverfehler."
  service_unavailable: "Dienst nicht verfügbar. Bitte versuchen Sie es später erneut."
  too_many_requests: "Zu viele Anfragen."
  missing_fields: "Erforderliche Felder fehlen."
  invalid_parameters: "Ungültige Parameter."
  method_not_allowed: "Methode nicht erlaubt."
  request_timeout: "Zeitüberschreitung der Anfrage."
general:
  ok: "OK"
  cancel: "Abbrechen"
  confirm: "Bestätigen"
  yes: "Ja"
  no: "Nein"
  back: "Zurück"
  next: "Weiter"
  close: "Schließen"
  save: "Speichern"
  delete: "Löschen"
  search: "Suchen"
  login: "Anmelden"
  logout: "Abmelden"
  sign_up: "Registrieren"
  profile: "Profil"
  settings: "Einstellungen"
  send: "Senden"
  submit: "Absenden"
  loading: "Wird geladen..."
  no_results: "Keine Ergebnisse gefunden."
  welcome: "Willkommen!"
  goodbye: "Auf Wiedersehen!"
  thank_you: "Danke."
  try_again: "Bitte versuchen Sie es erneut."
  contact_support: "Wenden Sie sich an den Support."
EOF

# Francés (fr.yaml)
cat << 'EOF' > locales/fr.yaml
errors:
  unexpected_error: "Une erreur inattendue s'est produite. Veuillez réessayer plus tard."
  invalid_credentials: "Nom d'utilisateur ou mot de passe incorrect."
  unauthorized: "Vous n'êtes pas autorisé à effectuer cette action."
  forbidden: "Accès refusé."
  not_found: "Ressource introuvable."
  user_not_found: "Utilisateur introuvable."
  email_exists: "Cette adresse e-mail est déjà utilisée."
  username_exists: "Ce nom d'utilisateur est déjà pris."
  account_disabled: "Ce compte a été désactivé."
  session_expired: "La session a expiré. Veuillez vous reconnecter."
  rate_limit: "Trop de demandes. Veuillez réessayer plus tard."
  server_error: "Erreur interne du serveur."
validation:
  required_field: "Ce champ est obligatoire."
  invalid_email: "Veuillez saisir une adresse e-mail valide."
  min_length: "Doit contenir au moins {min} caractères."
  max_length: "Doit contenir au maximum {max} caractères."
  password_mismatch: "Les mots de passe ne correspondent pas."
  invalid_format: "Format invalide."
  only_numbers: "Seules les valeurs numériques sont autorisées."
  min_value: "La valeur doit être au moins {min}."
  max_value: "La valeur doit être au maximum {max}."
  too_short: "Trop court."
  too_long: "Trop long."
notifications:
  new_message: "Nouveau message de {name}."
  friend_request: "Vous avez une nouvelle demande d'amitié."
  meeting_reminder: "Rappel : réunion \"{title}\" à {time}."
  task_due_soon: "La tâche \"{task}\" arrive bientôt à échéance."
  new_notification: "Vous avez une nouvelle notification."
  promo_offer: "Nouvelle offre promotionnelle disponible."
  account_approved: "Votre compte a été approuvé."
  account_rejected: "Votre compte a été refusé."
  update_available: "Une nouvelle mise à jour est disponible."
  event_starting: "L'événement \"{event}\" commence maintenant."
emails:
  welcome_subject: "Bienvenue sur Dialoom!"
  welcome_body: "Bonjour {name},\n\nMerci de vous être inscrit sur Dialoom. Nous sommes ravis de vous compter parmi nos utilisateurs. Si vous avez des questions, n'hésitez pas à contacter notre équipe d'assistance.\n\nCordialement,\nL'équipe Dialoom"
  reset_password_subject: "Réinitialisez votre mot de passe Dialoom"
  reset_password_body: "Bonjour {name},\n\nNous avons reçu une demande de réinitialisation de votre mot de passe. Cliquez sur le lien ci-dessous pour définir un nouveau mot de passe. Si vous n'êtes pas à l'origine de cette demande, veuillez ignorer cet e-mail.\n\nMerci,\nL'équipe d'assistance Dialoom"
  verify_email_subject: "Vérifiez votre adresse e-mail"
  verify_email_body: "Bonjour {name},\n\nVeuillez vérifier votre adresse e-mail en cliquant sur le lien ci-dessous. Si vous n'avez pas créé de compte Dialoom, vous pouvez ignorer cet e-mail.\n\nMerci,\nL'équipe Dialoom"
  password_changed_subject: "Votre mot de passe a été changé"
  password_changed_body: "Bonjour {name},\n\nNous vous confirmons que votre mot de passe a bien été modifié. Si vous n'êtes pas à l'origine de ce changement, veuillez contacter notre équipe d'assistance immédiatement.\n\nCordialement,\nL'équipe Dialoom"
api:
  created_success: "Créé avec succès."
  updated_success: "Mis à jour avec succès."
  deleted_success: "Supprimé avec succès."
  operation_success: "Opération réussie."
  operation_failed: "Opération échouée."
  invalid_token: "Jeton invalide."
  authentication_required: "Authentification requise."
  permission_denied: "Permission refusée."
  resource_not_found: "Ressource introuvable."
  bad_request: "Requête incorrecte."
  conflict_error: "Conflit détecté."
  server_error: "Erreur serveur."
  service_unavailable: "Service indisponible. Veuillez réessayer plus tard."
  too_many_requests: "Trop de demandes."
  missing_fields: "Champs obligatoires manquants."
  invalid_parameters: "Paramètres invalides."
  method_not_allowed: "Méthode non autorisée."
  request_timeout: "Délai d'attente dépassé."
general:
  ok: "OK"
  cancel: "Annuler"
  confirm: "Confirmer"
  yes: "Oui"
  no: "Non"
  back: "Retour"
  next: "Suivant"
  close: "Fermer"
  save: "Enregistrer"
  delete: "Supprimer"
  search: "Rechercher"
  login: "Connexion"
  logout: "Déconnexion"
  sign_up: "Inscription"
  profile: "Profil"
  settings: "Paramètres"
  send: "Envoyer"
  submit: "Valider"
  loading: "Chargement..."
  no_results: "Aucun résultat trouvé."
  welcome: "Bienvenue!"
  goodbye: "Au revoir!"
  thank_you: "Merci."
  try_again: "Veuillez réessayer."
  contact_support: "Contactez le support."
EOF

# Noruego (no.yaml)
cat << 'EOF' > locales/no.yaml
errors:
  unexpected_error: "Det oppstod en uventet feil. Vennligst prøv igjen senere."
  invalid_credentials: "Ugyldig brukernavn eller passord."
  unauthorized: "Du har ikke tillatelse til å utføre denne handlingen."
  forbidden: "Adgang nektet."
  not_found: "Ressurs ikke funnet."
  user_not_found: "Bruker ikke funnet."
  email_exists: "E-postadressen er allerede i bruk."
  username_exists: "Brukernavnet er allerede tatt."
  account_disabled: "Denne kontoen har blitt deaktivert."
  session_expired: "Økten er utløpt. Vennligst logg inn på nytt."
  rate_limit: "For mange forespørsler. Vennligst prøv igjen senere."
  server_error: "Intern serverfeil."
validation:
  required_field: "Dette feltet er obligatorisk."
  invalid_email: "Vennligst oppgi en gyldig e-postadresse."
  min_length: "Må være minst {min} tegn."
  max_length: "Må være maksimalt {max} tegn."
  password_mismatch: "Passordene samsvarer ikke."
  invalid_format: "Ugyldig format."
  only_numbers: "Kun numeriske verdier er tillatt."
  min_value: "Verdien må være minst {min}."
  max_value: "Verdien kan være høyst {max}."
  too_short: "For kort."
  too_long: "For lang."
notifications:
  new_message: "Ny melding fra {name}."
  friend_request: "Du har fått en ny venneforespørsel."
  meeting_reminder: "Påminnelse: møte \"{title}\" kl. {time}."
  task_due_soon: "Oppgaven \"{task}\" forfaller snart."
  new_notification: "Du har et nytt varsel."
  promo_offer: "Nytt kampanjetilbud er tilgjengelig."
  account_approved: "Kontoen din har blitt godkjent."
  account_rejected: "Kontoen din har blitt avvist."
  update_available: "En ny oppdatering er tilgjengelig."
  event_starting: "Arrangementet \"{event}\" starter nå."
emails:
  welcome_subject: "Velkommen til Dialoom!"
  welcome_body: "Hei {name},\n\nTakk for at du har registrert deg hos Dialoom. Vi er glade for å ha deg med oss. Hvis du har noen spørsmål, vennligst kontakt vårt supportteam.\n\nVennlig hilsen,\nDialoom-teamet"
  reset_password_subject: "Tilbakestill ditt Dialoom-passord"
  reset_password_body: "Hei {name},\n\nVi har mottatt en forespørsel om å tilbakestille ditt passord. Klikk på lenken nedenfor for å opprette et nytt passord. Hvis du ikke har bedt om dette, vennligst se bort fra denne e-posten.\n\nTakk,\nDialoom-supportteamet"
  verify_email_subject: "Bekreft din e-postadresse"
  verify_email_body: "Hei {name},\n\nVennligst bekreft din e-postadresse ved å klikke på lenken nedenfor. Hvis du ikke har opprettet en Dialoom-konto, kan du se bort fra denne e-posten.\n\nTakk,\nDialoom-teamet"
  password_changed_subject: "Ditt passord har blitt endret"
  password_changed_body: "Hei {name},\n\nDette er en bekreftelse på at ditt passord ble endret. Hvis du ikke utførte denne endringen, vennligst kontakt vår support umiddelbart.\n\nVennlig hilsen,\nDialoom-teamet"
api:
  created_success: "Opprettet."
  updated_success: "Oppdatert."
  deleted_success: "Slettet."
  operation_success: "Operasjonen ble fullført."
  operation_failed: "Operasjonen mislyktes."
  invalid_token: "Ugyldig token."
  authentication_required: "Autentisering kreves."
  permission_denied: "Ingen tilgang."
  resource_not_found: "Ressurs ikke funnet."
  bad_request: "Ugyldig forespørsel."
  conflict_error: "Konflikt oppstod."
  server_error: "Serverfeil."
  service_unavailable: "Tjenesten er utilgjengelig. Vennligst prøv igjen senere."
  too_many_requests: "For mange forespørsler."
  missing_fields: "Manglende obligatoriske felter."
  invalid_parameters: "Ugyldige parametere."
  method_not_allowed: "Metoden er ikke tillatt."
  request_timeout: "Tidsavbrudd for forespørsel."
general:
  ok: "OK"
  cancel: "Avbryt"
  confirm: "Bekreft"
  yes: "Ja"
  no: "Nei"
  back: "Tilbake"
  next: "Neste"
  close: "Lukk"
  save: "Lagre"
  delete: "Slett"
  search: "Søk"
  login: "Logg inn"
  logout: "Logg ut"
  sign_up: "Registrer deg"
  profile: "Profil"
  settings: "Innstillinger"
  send: "Send"
  submit: "Send inn"
  loading: "Laster..."
  no_results: "Ingen resultater funnet."
  welcome: "Velkommen!"
  goodbye: "Ha det bra!"
  thank_you: "Takk."
  try_again: "Vennligst prøv igjen."
  contact_support: "Kontakt support."
EOF

# Danés (da.yaml)
cat << 'EOF' > locales/da.yaml
errors:
  unexpected_error: "Der opstod en uventet fejl. Prøv venligst igen senere."
  invalid_credentials: "Ugyldigt brugernavn eller adgangskode."
  unauthorized: "Du har ikke tilladelse til at udføre denne handling."
  forbidden: "Adgang nægtet."
  not_found: "Ressource ikke fundet."
  user_not_found: "Bruger ikke fundet."
  email_exists: "Denne e-mailadresse er allerede i brug."
  username_exists: "Dette brugernavn er allerede optaget."
  account_disabled: "Denne konto er blevet deaktiveret."
  session_expired: "Sessionen er udløbet. Log venligst ind igen."
  rate_limit: "For mange forespørgsler. Prøv igen senere."
  server_error: "Intern serverfejl."
validation:
  required_field: "Dette felt er påkrævet."
  invalid_email: "Indtast venligst en gyldig e-mailadresse."
  min_length: "Skal være mindst {min} tegn."
  max_length: "Skal være højst {max} tegn."
  password_mismatch: "Adgangskoderne stemmer ikke overens."
  invalid_format: "Ugyldigt format."
  only_numbers: "Kun numeriske værdier er tilladt."
  min_value: "Værdien skal være mindst {min}."
  max_value: "Værdien skal være højst {max}."
  too_short: "For kort."
  too_long: "For lang."
notifications:
  new_message: "Ny besked fra {name}."
  friend_request: "Du har fået en ny venneanmodning."
  meeting_reminder: "Påmindelse: møde \"{title}\" kl. {time}."
  task_due_soon: "Opgaven \"{task}\" forfalder snart."
  new_notification: "Du har en ny meddelelse."
  promo_offer: "Nyt kampagnetilbud tilgængeligt."
  account_approved: "Din konto er blevet godkendt."
  account_rejected: "Din konto er blevet afvist."
  update_available: "En ny opdatering er tilgængelig."
  event_starting: "Begivenheden \"{event}\" starter nu."
emails:
  welcome_subject: "Velkommen til Dialoom!"
  welcome_body: "Hej {name},\n\nTak fordi du har tilmeldt dig Dialoom. Vi er glade for at have dig med om bord. Hvis du har spørgsmål, kontakt venligst vores supportteam.\n\nMed venlig hilsen,\nDialoom-teamet"
  reset_password_subject: "Nulstil din Dialoom-adgangskode"
  reset_password_body: "Hej {name},\n\nVi har modtaget en anmodning om at nulstille din adgangskode. Klik på linket nedenfor for at oprette en ny adgangskode. Hvis du ikke har anmodet om dette, skal du ignorere denne e-mail.\n\nTak,\nDialoom-supportteamet"
  verify_email_subject: "Bekræft din e-mailadresse"
  verify_email_body: "Hej {name},\n\nBekræft venligst din e-mailadresse ved at klikke på linket nedenfor. Hvis du ikke har oprettet en Dialoom-konto, kan du ignorere denne e-mail.\n\nTak,\nDialoom-teamet"
  password_changed_subject: "Din adgangskode er blevet ændret"
  password_changed_body: "Hej {name},\n\nDette er en bekræftelse på, at din adgangskode er blevet ændret. Hvis du ikke har foretaget denne ændring, kontakt venligst vores support med det samme.\n\nMed venlig hilsen,\nDialoom-teamet"
api:
  created_success: "Oprettet."
  updated_success: "Opdateret."
  deleted_success: "Slettet."
  operation_success: "Handlingen blev gennemført."
  operation_failed: "Handlingen mislykkedes."
  invalid_token: "Ugyldigt token."
  authentication_required: "Godkendelse påkrævet."
  permission_denied: "Tilladelse nægtet."
  resource_not_found: "Ressourcen blev ikke fundet."
  bad_request: "Ugyldigt anmodning."
  conflict_error: "Konfliktfejl."
  server_error: "Serverfejl."
  service_unavailable: "Tjenesten er utilgængelig. Prøv igen senere."
  too_many_requests: "For mange anmodninger."
  missing_fields: "Obligatoriske felter mangler."
  invalid_parameters: "Ugyldige parametre."
  method_not_allowed: "Metoden er ikke tilladt."
  request_timeout: "Forespørgslen overskred tidsgrænsen."
general:
  ok: "OK"
  cancel: "Annuller"
  confirm: "Bekræft"
  yes: "Ja"
  no: "Nej"
  back: "Tilbage"
  next: "Næste"
  close: "Luk"
  save: "Gem"
  delete: "Slet"
  search: "Søg"
  login: "Log ind"
  logout: "Log ud"
  sign_up: "Registrer dig"
  profile: "Profil"
  settings: "Indstillinger"
  send: "Send"
  submit: "Indsend"
  loading: "Indlæser..."
  no_results: "Ingen resultater fundet."
  welcome: "Velkommen!"
  goodbye: "Farvel!"
  thank_you: "Tak."
  try_again: "Prøv igen."
  contact_support: "Kontakt support."
EOF

# Italiano (it.yaml)
cat << 'EOF' > locales/it.yaml
errors:
  unexpected_error: "Si è verificato un errore imprevisto. Per favore riprova più tardi."
  invalid_credentials: "Nome utente o password non validi."
  unauthorized: "Non sei autorizzato a eseguire questa azione."
  forbidden: "Accesso negato."
  not_found: "Risorsa non trovata."
  user_not_found: "Utente non trovato."
  email_exists: "Questo indirizzo email è già in uso."
  username_exists: "Questo nome utente è già in uso."
  account_disabled: "Questo account è stato disabilitato."
  session_expired: "La sessione è scaduta. Effettua di nuovo l'accesso."
  rate_limit: "Troppe richieste. Riprova più tardi."
  server_error: "Errore interno del server."
validation:
  required_field: "Questo campo è obbligatorio."
  invalid_email: "Per favore, inserisci un indirizzo email valido."
  min_length: "Deve contenere almeno {min} caratteri."
  max_length: "Può contenere al massimo {max} caratteri."
  password_mismatch: "Le password non corrispondono."
  invalid_format: "Formato non valido."
  only_numbers: "Sono consentiti solo valori numerici."
  min_value: "Il valore deve essere almeno {min}."
  max_value: "Il valore deve essere al massimo {max}."
  too_short: "Troppo corto."
  too_long: "Troppo lungo."
notifications:
  new_message: "Nuovo messaggio da {name}."
  friend_request: "Hai una nuova richiesta di amicizia."
  meeting_reminder: "Promemoria: riunione \"{title}\" alle {time}."
  task_due_soon: "L'attività \"{task}\" scade a breve."
  new_notification: "Hai una nuova notifica."
  promo_offer: "Nuova offerta promozionale disponibile."
  account_approved: "Il tuo account è stato approvato."
  account_rejected: "Il tuo account è stato rifiutato."
  update_available: "È disponibile un nuovo aggiornamento."
  event_starting: "L'evento \"{event}\" sta iniziando ora."
emails:
  welcome_subject: "Benvenuto su Dialoom!"
  welcome_body: "Ciao {name},\n\nGrazie per esserti unito a Dialoom. Siamo entusiasti di averti con noi. Se hai domande, non esitare a contattare il nostro team di supporto.\n\nCordiali saluti,\nIl team di Dialoom"
  reset_password_subject: "Reimposta la tua password Dialoom"
  reset_password_body: "Ciao {name},\n\nAbbiamo ricevuto una richiesta di reimpostazione della tua password. Clicca sul link sottostante per impostare una nuova password. Se non hai richiesto questo, ignora questa email.\n\nGrazie,\nIl team di supporto Dialoom"
  verify_email_subject: "Verifica il tuo indirizzo email"
  verify_email_body: "Ciao {name},\n\nPer favore verifica il tuo indirizzo email cliccando sul link qui sotto. Se non hai creato un account Dialoom, puoi ignorare questa email.\n\nGrazie,\nIl team di Dialoom"
  password_changed_subject: "La tua password è stata cambiata"
  password_changed_body: "Ciao {name},\n\nTi confermiamo che la tua password è stata cambiata con successo. Se non hai effettuato questo cambiamento, contatta immediatamente il supporto.\n\nCordiali saluti,\nIl team di Dialoom"
api:
  created_success: "Creato con successo."
  updated_success: "Aggiornato con successo."
  deleted_success: "Eliminato con successo."
  operation_success: "Operazione completata con successo."
  operation_failed: "Operazione non riuscita."
  invalid_token: "Token non valido."
  authentication_required: "Autenticazione richiesta."
  permission_denied: "Permesso negato."
  resource_not_found: "Risorsa non trovata."
  bad_request: "Richiesta non valida."
  conflict_error: "Errore di conflitto."
  server_error: "Errore del server."
  service_unavailable: "Servizio non disponibile. Riprova più tardi."
  too_many_requests: "Troppe richieste."
  missing_fields: "Campi obbligatori mancanti."
  invalid_parameters: "Parametri non validi."
  method_not_allowed: "Metodo non consentito."
  request_timeout: "Timeout della richiesta."
general:
  ok: "OK"
  cancel: "Annulla"
  confirm: "Conferma"
  yes: "Sì"
  no: "No"
  back: "Indietro"
  next: "Avanti"
  close: "Chiudi"
  save: "Salva"
  delete: "Elimina"
  search: "Cerca"
  login: "Accedi"
  logout: "Esci"
  sign_up: "Registrati"
  profile: "Profilo"
  settings: "Impostazioni"
  send: "Invia"
  submit: "Invia"
  loading: "Caricamento..."
  no_results: "Nessun risultato trovato."
  welcome: "Benvenuto!"
  goodbye: "Arrivederci!"
  thank_you: "Grazie."
  try_again: "Per favore, riprova."
  contact_support: "Contatta il supporto."
EOF

# Polaco (pl.yaml)
cat << 'EOF' > locales/pl.yaml
errors:
  unexpected_error: "Wystąpił nieoczekiwany błąd. Spróbuj ponownie później."
  invalid_credentials: "Nieprawidłowa nazwa użytkownika lub hasło."
  unauthorized: "Nie masz uprawnień do wykonania tej akcji."
  forbidden: "Dostęp zabroniony."
  not_found: "Nie znaleziono zasobu."
  user_not_found: "Nie znaleziono użytkownika."
  email_exists: "Ten adres e-mail jest już używany."
  username_exists: "Ta nazwa użytkownika jest już zajęta."
  account_disabled: "To konto zostało dezaktywowane."
  session_expired: "Sesja wygasła. Zaloguj się ponownie."
  rate_limit: "Zbyt wiele żądań. Spróbuj ponownie później."
  server_error: "Wewnętrzny błąd serwera."
validation:
  required_field: "To pole jest wymagane."
  invalid_email: "Wprowadź prawidłowy adres e-mail."
  min_length: "Musi mieć co najmniej {min} znaków."
  max_length: "Może mieć maksymalnie {max} znaków."
  password_mismatch: "Hasła nie są zgodne."
  invalid_format: "Nieprawidłowy format."
  only_numbers: "Dozwolone są tylko wartości numeryczne."
  min_value: "Wartość musi wynosić co najmniej {min}."
  max_value: "Wartość może wynosić co najwyżej {max}."
  too_short: "Za krótki."
  too_long: "Za długi."
notifications:
  new_message: "Nowa wiadomość od {name}."
  friend_request: "Masz nowe zaproszenie do znajomych."
  meeting_reminder: "Przypomnienie: spotkanie \"{title}\" o {time}."
  task_due_soon: "Termin zadania \"{task}\" wkrótce upływa."
  new_notification: "Masz nowe powiadomienie."
  promo_offer: "Nowa oferta promocyjna dostępna."
  account_approved: "Twoje konto zostało zatwierdzone."
  account_rejected: "Twoje konto zostało odrzucone."
  update_available: "Dostępna jest nowa aktualizacja."
  event_starting: "Wydarzenie \"{event}\" właśnie się zaczyna."
emails:
  welcome_subject: "Witamy w Dialoom!"
  welcome_body: "Cześć {name},\n\nDziękujemy za dołączenie do Dialoom. Cieszymy się, że jesteś z nami. Jeśli masz jakiekolwiek pytania, skontaktuj się z naszym zespołem wsparcia.\n\nPozdrawiamy,\nZespół Dialoom"
  reset_password_subject: "Zresetuj swoje hasło w Dialoom"
  reset_password_body: "Cześć {name},\n\nOtrzymaliśmy prośbę o zresetowanie Twojego hasła. Kliknij poniższy link, aby ustawić nowe hasło. Jeśli nie wysłałeś tej prośby, zignoruj tę wiadomość.\n\nDziękujemy,\nZespół wsparcia Dialoom"
  verify_email_subject: "Potwierdź swój adres e-mail"
  verify_email_body: "Cześć {name},\n\nPotwierdź swój adres e-mail, klikając poniższy link. Jeśli nie tworzyłeś konta Dialoom, zignoruj tę wiadomość.\n\nDziękujemy,\nZespół Dialoom"
  password_changed_subject: "Twoje hasło zostało zmienione"
  password_changed_body: "Cześć {name},\n\nPotwierdzamy, że Twoje hasło zostało pomyślnie zmienione. Jeśli to nie Ty dokonałeś tej zmiany, natychmiast skontaktuj się z pomocą techniczną.\n\nPozdrawiamy,\nZespół Dialoom"
api:
  created_success: "Utworzono pomyślnie."
  updated_success: "Zaktualizowano pomyślnie."
  deleted_success: "Usunięto pomyślnie."
  operation_success: "Operacja zakończona pomyślnie."
  operation_failed: "Operacja nie powiodła się."
  invalid_token: "Nieprawidłowy token."
  authentication_required: "Wymagane uwierzytelnienie."
  permission_denied: "Brak uprawnień."
  resource_not_found: "Nie znaleziono zasobu."
  bad_request: "Nieprawidłowe żądanie."
  conflict_error: "Błąd konfliktu."
  server_error: "Błąd serwera."
  service_unavailable: "Usługa niedostępna. Spróbuj ponownie później."
  too_many_requests: "Zbyt wiele żądań."
  missing_fields: "Brak wymaganych pól."
  invalid_parameters: "Nieprawidłowe parametry."
  method_not_allowed: "Metoda niedozwolona."
  request_timeout: "Przekroczono limit czasu żądania."
general:
  ok: "OK"
  cancel: "Anuluj"
  confirm: "Potwierdź"
  yes: "Tak"
  no: "Nie"
  back: "Wstecz"
  next: "Dalej"
  close: "Zamknij"
  save: "Zapisz"
  delete: "Usuń"
  search: "Szukaj"
  login: "Zaloguj się"
  logout: "Wyloguj się"
  sign_up: "Zarejestruj się"
  profile: "Profil"
  settings: "Ustawienia"
  send: "Wyślij"
  submit: "Prześlij"
  loading: "Ładowanie..."
  no_results: "Nie znaleziono wyników."
  welcome: "Witamy!"
  goodbye: "Do widzenia!"
  thank_you: "Dziękujemy."
  try_again: "Spróbuj ponownie."
  contact_support: "Skontaktuj się z pomocą techniczną."
EOF

# Holandés (nl.yaml)
cat << 'EOF' > locales/nl.yaml
errors:
  unexpected_error: "Er is een onverwachte fout opgetreden. Probeer het later opnieuw."
  invalid_credentials: "Ongeldige gebruikersnaam of wachtwoord."
  unauthorized: "Je bent niet bevoegd om deze actie uit te voeren."
  forbidden: "Toegang geweigerd."
  not_found: "Bron niet gevonden."
  user_not_found: "Gebruiker niet gevonden."
  email_exists: "Dit e-mailadres is al in gebruik."
  username_exists: "Deze gebruikersnaam is al in gebruik."
  account_disabled: "Dit account is gedeactiveerd."
  session_expired: "Sessie verlopen. Log opnieuw in."
  rate_limit: "Te veel aanvragen. Probeer het later opnieuw."
  server_error: "Interne serverfout."
validation:
  required_field: "Dit veld is verplicht."
  invalid_email: "Vul een geldig e-mailadres in."
  min_length: "Moet minimaal {min} tekens bevatten."
  max_length: "Mag maximaal {max} tekens bevatten."
  password_mismatch: "Wachtwoorden komen niet overeen."
  invalid_format: "Ongeldig formaat."
  only_numbers: "Alleen numerieke waarden zijn toegestaan."
  min_value: "Waarde moet minimaal {min} zijn."
  max_value: "Waarde mag maximaal {max} zijn."
  too_short: "Te kort."
  too_long: "Te lang."
notifications:
  new_message: "Nieuw bericht van {name}."
  friend_request: "Je hebt een nieuw vriendverzoek."
  meeting_reminder: "Herinnering: vergadering \"{title}\" om {time}."
  task_due_soon: "Taak \"{task}\" verloopt binnenkort."
  new_notification: "Je hebt een nieuwe melding."
  promo_offer: "Nieuwe promotionele aanbieding beschikbaar."
  account_approved: "Je account is goedgekeurd."
  account_rejected: "Je account is afgekeurd."
  update_available: "Een nieuwe update is beschikbaar."
  event_starting: "Het evenement \"{event}\" begint nu."
emails:
  welcome_subject: "Welkom bij Dialoom!"
  welcome_body: "Hallo {name},\n\nBedankt voor je aanmelding bij Dialoom. We zijn blij dat je erbij bent. Als je vragen hebt, neem dan gerust contact op met ons ondersteuningsteam.\n\nMet vriendelijke groet,\nHet Dialoom-team"
  reset_password_subject: "Stel je Dialoom-wachtwoord opnieuw in"
  reset_password_body: "Hallo {name},\n\nWe hebben een verzoek ontvangen om je wachtwoord opnieuw in te stellen. Klik op de onderstaande link om een nieuw wachtwoord in te stellen. Als je deze aanvraag niet hebt gedaan, kun je deze e-mail negeren.\n\nBedankt,\nDialoom ondersteuning"
  verify_email_subject: "Bevestig je e-mailadres"
  verify_email_body: "Hallo {name},\n\nBevestig je e-mailadres door op de onderstaande link te klikken. Als je geen Dialoom-account hebt aangemaakt, kun je deze e-mail negeren.\n\nBedankt,\nHet Dialoom-team"
  password_changed_subject: "Je wachtwoord is gewijzigd"
  password_changed_body: "Hallo {name},\n\nDit is een bevestiging dat je wachtwoord succesvol is gewijzigd. Als je deze wijziging niet hebt uitgevoerd, neem dan onmiddellijk contact op met onze ondersteuning.\n\nMet vriendelijke groet,\nHet Dialoom-team"
api:
  created_success: "Met succes aangemaakt."
  updated_success: "Met succes bijgewerkt."
  deleted_success: "Met succes verwijderd."
  operation_success: "Bewerking succesvol voltooid."
  operation_failed: "Bewerking mislukt."
  invalid_token: "Ongeldige token."
  authentication_required: "Authenticatie vereist."
  permission_denied: "Toestemming geweigerd."
  resource_not_found: "Bron niet gevonden."
  bad_request: "Ongeldig verzoek."
  conflict_error: "Conflictfout."
  server_error: "Serverfout."
  service_unavailable: "Dienst niet beschikbaar. Probeer het later opnieuw."
  too_many_requests: "Te veel verzoeken."
  missing_fields: "Verplichte velden ontbreken."
  invalid_parameters: "Ongeldige parameters."
  method_not_allowed: "Methode niet toegestaan."
  request_timeout: "Time-out van verzoek."
general:
  ok: "OK"
  cancel: "Annuleren"
  confirm: "Bevestigen"
  yes: "Ja"
  no: "Nee"
  back: "Terug"
  next: "Volgende"
  close: "Sluiten"
  save: "Opslaan"
  delete: "Verwijderen"
  search: "Zoeken"
  login: "Inloggen"
  logout: "Uitloggen"
  sign_up: "Registreren"
  profile: "Profiel"
  settings: "Instellingen"
  send: "Verzenden"
  submit: "Indienen"
  loading: "Laden..."
  no_results: "Geen resultaten gevonden."
  welcome: "Welkom!"
  goodbye: "Tot ziens!"
  thank_you: "Bedankt."
  try_again: "Probeer het opnieuw."
  contact_support: "Neem contact op met de ondersteuning."
EOF

echo "Archivos YAML de idiomas generados correctamente en el directorio 'locales'."
